### ISSUE TITLE
mypy.ini per-file options not respected

### ISSUE THREAD

**Issue by msherry** [msherry/flycheck-pycheckers#2]
Flycheck actually runs its checkers over a file named `flycheck_<real_file_name>.py`, which causes the file-specific sections in mypy.ini files not to match anything. E.g., for the config file
```conf
[mypy]
platform = darwin
follow_imports = skip
ignore_missing_imports = True
warn_redundant_casts = True
warn_no_return = True
show_traceback = True
strict_optional = True

[mypy-path.to.file.heres_a_file]
strict_optional = False
```
the options in the `[mypy]` section will be correctly applied when checking file `heres_a_file.py`, but the specific options will not, since flycheck will see it as `flycheck_heres_a_file.py`.

**Comment by gvanrossum** [comment]
Might want to look into mypy's `--shadow-file` option, which was made for this purpose. (It only works for one file though.)
