### ISSUE TITLE
flake8 config is ignored

### ISSUE THREAD

**Issue by apnewberry** [msherry/flycheck-pycheckers#29]
I have a .flake8 and setup.cfg with `ignore = C812` (trailing commas). The warning does not appear when running flake8 manually, but I still get the flake8 message about `cli.py` from flycheck-pycheckers. It does work if I put `extra_ignore_codes = C812`, but that seems like it shouldn't be necessary.

Here's a demo repo https://github.com/apnewberry/demo

flycheck-pycheckers 0.11.5
flake8 3.5.0 (flake8_commas: 2.0.0, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.6 on Linux
emacs 26.1
python 3.6
ubuntu 18.04

Related issue: https://github.com/msherry/flycheck-pycheckers/issues/12

**Comment by msherry** [comment]
Thanks for the report! I'll take a look at this and see what I can do.

I notice that you have `flake8_commas` installed -- presumably you have a good reason for this, but it looks like it doesn't get installed by default, and I don't get this error message unless I install that package manually. As a temporary workaround for this specific error only (in addition to the ones you've already named, of course), you could stop installing that package if you don't want it to actually report this error. Obviously this isn't a solution to the more general problem of the flake8 config file being ignored.

**Comment by msherry** [comment]
@apnewberry This should be resolved, please let me know your results (I tested with your example repo and it worked for me). Please note that issues mentioned in #12 are still in effect, so you will essentially have to figure out the interaction with `flycheck-pycheckers-ignore-codes` locally -- I set that variable to nil to test this.

**Comment by apnewberry** [comment]
Thanks for looking into it! I upgraded to `Flycheck-Pycheckers 0.11-6-g163443f` but see no change in the behavior while flake8-commas is installed (good point about the plugin!). I'll go with `extra_ignore_codes` for now.

I use flake8-commas for its "[C818] trailing comma on bare tuple prohibited" option to avoid accidental tuples like 
```
x = f(
    arg1,
    arg2,
),
```

**Comment by msherry** [comment]
Oops, note that `--extend-ignore` is only available in flake8 3.6.0, and it looks like you're running 3.5.0. I think this flag was added to enable what I'm trying to do here, but I'm not sure how to accomplish this behavior beyond what was done in #12 without it.

**Comment by apnewberry** [comment]
Yep that works, thank you!

**Comment by liebkne** [comment]
@msherry Hi, I can't get the package work with `setup.cfg` (simply been ignored). Do I need extra setup for that? Thanks!

**Comment by msherry** [comment]
@liebkne Can you open a new issue with enough information for me to help debug the issue? It seems like the latest version of flycheck-pycheckers should support `setup.cfg` based on the resolution of this ticket, so your issue sounds separate from this one.
