### ISSUE TITLE
Pycheckers not returning casing errors for pylint

### ISSUE THREAD

**Issue by billywade** [msherry/flycheck-pycheckers#32]
Hi there! I'm getting different results running pylint via pycheckers and pylint via flycheck. Here's where I am so far:

https://github.com/flycheck/flycheck/issues/1544

Thanks!

**Comment by msherry** [comment]
Hi, @billywade ! Thanks for your report! It looks like most of the errors that you've highlighted are ones that flycheck-pycheckers ignores by default. This is an opinionated decision that I made back when I first released this, and perhaps it doesn't hold up well now -- my apologies for the confusion.

You can customize the value of [`flycheck-pycheckers-ignore-codes`](https://github.com/msherry/flycheck-pycheckers//blob/master/flycheck-pycheckers.el#L189) to remove these codes, and then flycheck should report on them correctly. The default value for this variable is `("C0411" "C0413" "C0103" "C0111" "W0142" "W0201" "W0232" "W0403" "W0511" "E1002" "E1101" "E1103" "R0201" "R0801" "R0903" "R0904" "R0914")` -- you can set it to `nil`, or remove any or all codes that apply to your situation. This can be done through the `customize-variable` interface, as well.

**Comment by billywade** [comment]
Great, thanks boss!
