### ISSUE TITLE
Default line width does not match checker's defaults

### ISSUE THREAD

**Issue by rafalcieslak** [msherry/flycheck-pycheckers#35]
`pycheckers` uses the [default max-line-width of 80](https://github.com/msherry/flycheck-pycheckers/blob/30cc72c80dcda671e04054eb2a7b167419f4ae86/bin/pycheckers.py#L1034) - which is different to `flake8` default (79), PEP8 recommendation (79) and pylint default (also 79).

This discrepancy means that if I use `pycheckers` on a project that does not customize this value in `.pycheckers` file, and there are 80 characters in some lines, then 

 - running any checker (e.g. `flake8`) from command-line correctly reports line-too-long errors
 - `pycheckers` does **not** report any errors

Of course I can circumvent this by setting the line width limit to 79 in the `.pycheckers` configuration, but I suppose a wrapper around other checkers should not introduce any code style bias by using different defaults than the checkers it wraps.

**Comment by msherry** [comment]
Thanks for reporting! That's fair -- I've deliberately made pycheckers opinionated in some areas, but it doesn't make sense to be opinionated for a small thing like this. If you want, I'll review and accept a patch modifying this behavior, or I can try to get to it in my spare time.
