### ISSUE TITLE
Way to disable some of sane_default_ignore_codes

### ISSUE THREAD

**Issue by JulienPalard** [msherry/flycheck-pycheckers#4]
Looks like `bin/pycheckers.py` is declaring an "opinionated" list of safe-to-ignore codes, but I prefer using per-project `pylintrc` files for this.

It does not look like there is a way to deactivate those defaults (however LintRunner excepts a never given `use_sane_defaults` parameter defaulting to `True`. As it's given, it's always `True`).

I'd propose to completly remove the `sane_default_ignore_code` from the `pycheckers.py` file and move them all to the default of flycheck-pycheckers-ignore-codes. It should not change the current behavior, but it would allow one to manually remove them from their emacs configuration. Is it a good idea? I can try to implement it if it looks good.

**Comment by msherry** [comment]
Yes, I definitely got lazy when implementing the sane default ignores -- I picked something that worked for me, and then never gave it much thought. If you'd like to refactor this into something more useful, I would certainly appreciate it!
