### ISSUE TITLE
This is a bug? Or my wrong?

### ISSUE THREAD

**Issue by EvanMeek** [msherry/flycheck-pycheckers#52]
![flycheck-bug](https://user-images.githubusercontent.com/27056033/78921099-fa51ce80-7ac6-11ea-96b0-e1898b29f155.png)

**Comment by EvanMeek** [comment]
Python(3.8.2) code.

**Comment by msherry** [comment]
Hi there. Thanks for creating an issue!

It's hard to tell what's going on in your screenshot. Is it that errors are superimposed on the code itself? If so, that's not intended, but I'm not sure how flycheck-pycheckers would be causing this itself -- the elisp for this project is very simple, and is limited to running, and parsing the output of, a python script.

Are you perhaps using something like https://github.com/flycheck/flycheck-popup-tip or https://github.com/flycheck/flycheck-pos-tip? If you can include some instructions on how to reproduce, I can try to investigate, but I strongly suspect some other package is causing this.

If I've misunderstood your report entirely, then my apologies! Please describe the issue in a couple words so I can have a starting point for an investigation. Thanks!

**Comment by EvanMeek** [comment]
> Hi there. Thanks for creating an issue!
> 
> It's hard to tell what's going on in your screenshot. Is it that errors are superimposed on the code itself? If so, that's not intended, but I'm not sure how flycheck-pycheckers would be causing this itself -- the elisp for this project is very simple, and is limited to running, and parsing the output of, a python script.
> 
> Are you perhaps using something like https://github.com/flycheck/flycheck-popup-tip or https://github.com/flycheck/flycheck-pos-tip? If you can include some instructions on how to reproduce, I can try to investigate, but I strongly suspect some other package is causing this.
> 
> If I've misunderstood your report entirely, then my apologies! Please describe the issue in a couple words so I can have a starting point for an investigation. Thanks!
Thank you very much for your prompt reply. This Python program can run, but it prompts for syntax errors, which makes me a little confused. Maybe this problem is not caused by "pycodestyle", but by pyflakes. The way to reproduce is to write my code into a buffer, and then turn on code checking. PS: my English is not very good. If you can't understand it, please point it out for me. I'll try my best to change the way of saying so that you can understand it. Thank you for your help.

**Comment by EvanMeek** [comment]
Thank you very much for your prompt reply. This Python program can run, but it prompts for syntax errors, which makes me a little confused. Maybe this problem is not caused by "pycodestyle", but by pyflakes. The way to reproduce is to write my code into a buffer, and then turn on code checking. PS: my English is not very good. If you can't understand it, please point it out for me. I'll try my best to change the way of saying so that you can understand it. Thank you for your help.

**Comment by msherry** [comment]
Can you paste the actual code that is being checked? It looks like some of it is hidden by the error messages. In particular, I see error messages related to semicolons (`;`), but I don't actually see `;` in your code, so it's hard to figure out what it's talking about.

**Comment by EvanMeek** [comment]
The code was modified because the error could not be fixed at that time. And because of the past few hours, I can't remember what the specific code is, but I recovered through undo, but there was no error. I don't see ";" in the code, so I can't reproduce it.Sorry.
