### ISSUE TITLE
*_command not taken into account when validating whether checker exists

### ISSUE THREAD

**Issue by posita** [msherry/flycheck-pycheckers#53]
The `{}_command` parameter is not taken into account when when calling `self._executable_exists()` in [`pycheckers.py#L440`](https://github.com/msherry/flycheck-pycheckers/blob/44b11b51c97fd334ecdce74169c0e65123ef5991/bin/pycheckers.py#L440). It's first considered via `self.construct_args(…)` which doesn't happen until [`pycheckers.py#L459`](https://github.com/msherry/flycheck-pycheckers/blob/44b11b51c97fd334ecdce74169c0e65123ef5991/bin/pycheckers.py#L459). The net effect is that if you're overriding, e.g., `mypy_command = /usr/local/bin/mypy-daemon` as documented, you still need to have an executable called `mypy` (or `dmypy`, depending) **_somewhere_** in your path, _even if it will never be called_. (Consider the work-around where you do something like `ln -s /bin/true /usr/local/bin/mypy`.)

**Comment by msherry** [comment]
Oh, good catch. I'll see if I can get a fix up later this week (pull requests gratefully accepted as well, of course :) )

I don't really want to be splitting up the `{}_command` param into parts and checking if the first one exists, since that sounds ugly. Would it make sense to just not do the existence check if the user has provided their own command?

**Comment by posita** [comment]
> Oh, good catch. I'll see if I can get a fix up later this week (pull requests gratefully accepted as well, of course :) )
> 
> I don't really want to be splitting up the `{}_command` param into parts and checking if the first one exists, since that sounds ugly. Would it make sense to just not do the existence check if the user has provided their own command?

Ah, crap. I just submitted #54 that does exactly that. Let me check to see what happens if the check is omitted and see what the UX is like.
