### ISSUE TITLE
Incorrect use of "define-obsolete-variable-alias"

### ISSUE THREAD

**Issue by lbolla** [msherry/flycheck-pycheckers#59]
The use of `define-obsolete-variable-alias` is wrong here:
https://github.com/msherry/flycheck-pycheckers/blob/e8ce874eea4bba13aead8eb8e0262e94fb51f25e/flycheck-pycheckers.el#L206

On Emacs tip, that function requires a third parameter, `when`:
```
(define-obsolete-variable-alias OBSOLETE-NAME CURRENT-NAME WHEN &optional
DOCSTRING)
```

Emacs version: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2021-03-31

**Comment by lbolla** [comment]
See also https://emba.gnu.org/emacs/emacs/-/commit/32c6732d16385f242b1109517f25e9aefd6caa5c

and a similar report in another project: https://github.com/manateelazycat/emacs-application-framework/pull/509

**Comment by hjpotter92** [comment]
And also at Malabarba/smart-mode-line#251

**Comment by msherry** [comment]
Thanks for pointing out this issue! Pull requests are gratefully accepted, otherwise I'll have to see when I can get to this.
