### ISSUE TITLE
 flycheck-pycheckers - what is the purpose of this package?

### ISSUE THREAD

**Issue by rdbeni0** [msherry/flycheck-pycheckers#68]
hi, i am trying to understand why we have package like "flycheck-pycheckers"?

currerntly in my python-mode i am using flycheck and i have below checkers: **python-flake8**, **python-pylint**, **python-pycompile**. I can easily add more if i want, but i dont need it.

so when i will run **M-x flycheck-list-errors** then i have table with errors which are provided by different checkers. So i can see that errors are validating via multiple engines.

so in this case - is this package still needed & useful?

**Comment by msherry** [comment]
Thanks for your feedback! I certainly don't want anyone to feel like they have to use this package, so if you don't find it useful, please feel free to use something that better suits your needs :)
